### ISSUE TITLE
Error running the new apply-registry script on Windows 11

### ISSUE THREAD

**Issue by 0450** [amitxv/PC-Tuning#121]
```
> C:\bin\scripts\apply-registry.ps1 -winver 11
error: failed merging one or more registry files
```
Made sure I was running as Administrator and rebooted several times.

Had used the scripts on Windows 11 back in March 2023 with no issues.

**Comment by amitxv** [comment]
I'm aware, I have been working on a workaround today. Will let you know when it is fixed

**Comment by amitxv** [comment]
Fixed in https://github.com/amitxv/PC-Tuning/commit/9d1b54e13bb9ad78649bddcfe40213b44bfb3060. Please read commit description for more details. You need to build a new ISO because the Appx package removal step has been moved to post-install.

**Comment by 0450** [comment]
built a new ISO with the new files, received the same error on a different step.
```
> C:\bin\scripts\apply-registry.ps1 -winver 11
info: this may take a while...
error: failed merging one or more registry files
```
