### ISSUE TITLE
.PS1 for Firefox Install, is it possible to do it with FireFox Developer Edition?

### ISSUE THREAD

**Issue by Harv-st** [amitxv/PC-Tuning#122]
Since FireFox right now removed the possibility to have Permanent Plug-Ins that do not have a signature (Which most of the useful ones from GitHub are), would it be possible to make the same .ps1 but for FireFox Developer Edition since it allows the use of these Plug-Ins permanently?

**Comment by amitxv** [comment]
Implemented in https://github.com/amitxv/PC-Tuning/commit/14bfe026a8a70e76afdffd157ea1b4e4fb7bcf7c. See image below for the changes required to install an unsigned extension in the same directory as a script (or specify the full directory)

![image](https://github.com/amitxv/PC-Tuning/assets/86924251/41148418-ea73-44be-8511-e0149cdae0ef)
