### ISSUE TITLE
services

### ISSUE THREAD

**Issue by dcxml** [amitxv/PC-Tuning#138]
Services-Disable with minimal-services.ini breaks nvidia control panel and nvidia drivers installation.

**Comment by dcxml** [comment]
On win 11 22h2

**Comment by dcxml** [comment]
need to enable nvidia container ls service in services.msc.

**Comment by amitxv** [comment]
1. The GPU driver installation step in post-install is placed before the services step deliberately for this reason
2. The NVIDIA container service which is responsible for the control panel is disabled after running ``Services-Disable.bat`` as it wastes CPU cycles and forces unnecessary context switches. Most of the time, it is not required after configuring driver-level settings
