### ISSUE TITLE
Mullvad no longer loads

### ISSUE THREAD

**Issue by axxg3l** [amitxv/PC-Tuning#139]
After following the guide Mullvad VPN does work before running the "Services-Disable.bat" file I generated; however, after running this file Mullvad VPN now outputs a "Connecting to Mullvad system service" message. 
![image](https://github.com/amitxv/PC-Tuning/assets/69566373/e7ce5b72-8088-4ed7-89b5-5d195ea32e06)

<details>
  <summary>I've gone to services and found the specific Mullvad system service titled "Mullvad VPN Service" and attempting to start it returns this error, and checking the Dependencies tab doesn't really show much.</summary>
  
![image](https://github.com/amitxv/PC-Tuning/assets/69566373/8a177186-d597-4916-a657-2f2d9457e0aa)
![image](https://github.com/amitxv/PC-Tuning/assets/69566373/cbe6b4a0-6ff9-4abe-9041-06838658cfb2)

</details>

<details>
  <summary>When generating my Services batch files I used these for the ini file:</summary>
  
````
[automatic]
AudioEndpointBuilder
AudioSrv
Audiosrv
BrokerInfrastructure
CoreMessagingRegistrar
DcomLaunch
gpsvc
Power
RpcEptMapper
RpcSs
sppsvc
ProfSvc
LSM
UserManager
TextInputManagementService
MMCSS
nsi # Required for: Win11, Wi-Fi, Applications (Apex Legends, COD: Cold War, Valorant, Uplay)
NlaSvc # Required for: Wi-Fi
EventLog # Required for: Wi-Fi
Wcmsvc # Required for: Wi-Fi
Wlansvc # Required for: Wi-Fi
WlanSvc # Required for: Wi-Fi
Dhcp # Required for: Wi-Fi

[manual]
CryptSvc
TrustedInstaller
msiserver
Winmgmt
Appinfo # Required for: UAC (if removed, must have the UAC disabled by setting the EnableLUA registry key set to 0)
PlugPlay # Required for: Win7
camsvc # Required for: Camera, Microphone only on Win10 1803+
AppXSvc # Required for: Win10 1803, Win11
StateRepository # Required for: Win10 1803+
seclogon # Required for: Applications (FrameView)
netprofm # Required for: Win11, Wi-Fi
Netman # Required for: Wi-Fi
NetSetupSvc # Required for: Wi-Fi

[disable_drivers]
acpipagr
lltdio
PEAUTH
rspndr
secdrv
tcpipreg
CLFS
fvevol
KSecPkg
rdyboost
storflt
AsyncMac
bowser
Beep
blbdrive
DfsC
mpsdrv
mrxsmb
mrxsmb10
mrxsmb20
NetBIOS
NetBT
rdbss
srv
srv2
srvnet
tunnel
Wanarpv6
WmiAcpi
discache
RDPCDD
RDPENCDD
RDPREFMP
bindflt
CldFlt
MsLldp
Ndu
storqosflt
wanarp
wcifs
iorate
MsSecFlt
SgrmAgent
spaceport
Telemetry
WindowsTrustedRT
WindowsTrustedRTProxy
amdgpio2
GPIOClx0101
kdnic
UEFI
afunix
bam
cdrom
CimFS
GpuEnergyDrv
NdisCap
npsvctrig
Vid
EhStorClass
CompositeBus
NdisVirtualBus
rdpbus
umbus
vdrvroot
MSKSSRV
MSTEE
NdisWan
PptpMiniport
RasAgileVpn
Rasl2tp
RasPppoe
RasSstp
Wof
bfs
IntelPMT
PRM
MsSecCore
UnionFS
ksthunk
luafv

# BasicDisplay # Uncommenting breaks: Basic Display Driver, Safe mode, potentially the OS when restarting the GPU driver. GPU drivers must be installed
# VgaSave # Equivalent to BasicDisplay on older operating systems
# ahcache # Uncommenting breaks: Fullscreen, Legacy Flip presentation mode for a minority of applications
# swenum # Uncommenting breaks: Camera
# vwififlt # Uncommenting breaks: Wi-Fi
# tdx # Uncommenting breaks: Wi-Fi
# volsnap # Uncommenting breaks: Win8 and lower
# mssmbios # Uncommenting breaks: Applications (GTA)
# volmgrx # Uncommenting breaks: Dynamic Volumes, Raid
# msisadrv # Uncommenting breaks: Keyboard on mobile devices
# Psched # Uncommenting breaks: QoS policies, may lead to delayed network initialization at boot if disabled
# pcw # Uncommenting breaks: Stock Task Manager (use process explorer as an alternative)
# FileCrypt # Uncommenting breaks: FACEIT

[rename_binaries]
C:\Windows\System32\RuntimeBroker.exe
C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
````
</details>

It's not a big deal, I can just revert to my normal services, however, I'd like to use Mullvad with minimal services enabled.

Edit: also noticed the volume dial on my keyboard no longer works nor does the taskbar icon, I've restored the taskbar icon in a way buy using eartrumpet.
~~Edit 2: now noticing when opening Valorant clicking on the shortcut freezes my computer for about 40 seconds to a minute then it un-freezes and the game loads; downloading and testing to see if this issue is with all games.~~ The problem randomly no longer exists. However when fullscreening anything the taskbar remains above it, Including even just watching YouTube videos on Firefox.

**Comment by amitxv** [comment]
1. See [debug-services.md](https://github.com/amitxv/PC-Tuning/blob/main/docs/debug-services.md) in regards to identifying what services are required for an application to function
2. I believe ``hidserv`` is the service responsible for media keys. The volume icon is not supposed to disappear but the flyout is disabled
3. Disabling ``ShellExperienceHost.exe`` is responsible for the taskbar bug but you can simply restart explorer.exe in Task Manager
