### ISSUE TITLE
Microphone doesn't work

### ISSUE THREAD

**Issue by kapselegg** [amitxv/PC-Tuning#141]
mic doesnt work after use (win11)

**Comment by amitxv** [comment]
Is the ``camsvc`` service enabled as it is required for microphone access in ``minimal-services.ini``? If not, change the start value from 4 to 2 in ``Services-Disable.bat``.
https://github.com/amitxv/PC-Tuning/blob/7cc8cc01d26055d8e6e0278e84e092c0e80c18c8/bin/minimal-services.ini#L32

**Comment by amitxv** [comment]
@kapselegg any update on this?
