### ISSUE TITLE
RWEverything is blocked by FACEIT anticheat

### ISSUE THREAD

**Issue by ndunnett** [amitxv/PC-Tuning#155]
FYI FACEIT blocks the RWE driver from loading, and allegedly Vanguard does as well. Any suggestions for other methods to disable XHCI Interrupt Moderation?

**Comment by amitxv** [comment]
Valorant was fine for me but I haven't played in a while. People were reporting that FACEIT does not complain about the alternative linked below but I have not tested it. In terms of my IMOD script, I will need to see whether it supports writing to and reading from 32-bit DWORD addresses.

https://github.com/Faintsnow/HE

**Comment by ndunnett** [comment]
Looks like HE can indeed read and write DWORD addresses with FACEIT running, I did some small tests manually setting IMOD intervals through command prompt in HE, however documentation is near on non-existent and it has very limited CLI support. Reading the author's comment on this issue [here](https://github.com/Faintsnow/HE/issues/5#issuecomment-1171930630) I have an idea on how to adapt your script to make it work, it won't be pretty but I'll share it here if I come up with something.

**Comment by ndunnett** [comment]
I've finally come back to this and forked your script to work with HE. It's not exactly nice as it opens/closes HE multiple times in the foreground, however it is fully automatic and doesn't clash with FACEIT, so I suppose it is better than nothing.

https://gist.github.com/ndunnett/233f9c30d64229cc124995f58c6cd7e3
