### ISSUE TITLE
Nvidia Setup Suggestion 

### ISSUE THREAD

**Issue by SVSQUVSH** [amitxv/PC-Tuning#156]
There is a great Tool called "NVCleanstall". It's a really handy way to strip down Nvidia Drivers. 
You have the option to disable telemetry, disable HDCP or MPO and even enabling MSI mode for the GPU (and set the corresponding Priority). 
![Capture](https://github.com/amitxv/PC-Tuning/assets/90634238/2499d913-8adf-4641-bb0e-3ff11dd9ea65)

It saves alot of time, because you have everything packed inside that program. 
Chris Titus Tech also made a Video about it and recommended it. 
I scanned it for Malware on VirusTotal.com to be sure, and only got 1 alert (false positive).

Would love to see it inside your awesome Guide!

**Comment by SVSQUVSH** [comment]
Btw, there is also the Option "disable driver telemetry (Experimental)", which got added a while ago. I don't recommend using that, but me personally, I didn't encounter any issues with it.

**Comment by amitxv** [comment]
- Instruction to disable HDCP can be found [here](https://github.com/amitxv/PC-Tuning/blob/main/docs/configure-nvidia.md#disable-hdcp-required-for-drm-content).
- Instruction to disable MPOs can be found [here](https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#presentation-mode)
- MSIs and IRQ priorities are explained in [this](https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#message-signaled-interrupts) section
- NVCleanstall's installer adware removal can be found [here](https://github.com/amitxv/PC-Tuning/blob/main/docs/configure-nvidia.md#strip-and-install-the-driver) by editing ``NVI2\presentations.cfg``

The *disable telemetry* option modifies the INF and this is the output of sigverif:
![image](https://github.com/amitxv/PC-Tuning/assets/86924251/b04fdedb-8cbf-4338-97d6-e349b2549c6e)

The NVIDIA container service is implicitly disabled in my [services config](https://github.com/amitxv/PC-Tuning/blob/main/bin/minimal-services.ini) as it is not included in there which prevents:

![image](https://github.com/amitxv/PC-Tuning/assets/86924251/7cf4b3df-7e12-4f8b-a147-09d0f1869f08)

I would prefer to stay away from this tool.
