### ISSUE TITLE
"GlobalTimerResolutionRequests" Alternative?

### ISSUE THREAD

**Issue by N-NNoThing** [amitxv/PC-Tuning#157]
"GlobalTimerResolutionRequests" only works on server 2022+ and Windows 11+
But what about older versions? :(

This is what i get when i open "MeasureSleep.exe" its just not working :(
Resolution: 0.4990ms, Sleep(1) slept 8.7430ms (delta: 7.7430)
Resolution: 0.4990ms, Sleep(1) slept 15.4387ms (delta: 14.4387)
Resolution: 0.4990ms, Sleep(1) slept 15.4072ms (delta: 14.4072)
Resolution: 0.4990ms, Sleep(1) slept 15.4279ms (delta: 14.4279)
Resolution: 0.4990ms, Sleep(1) slept 15.5268ms (delta: 14.5268)

Windows 10 LTSC 21H2 build 19044.2546

**Comment by amitxv** [comment]
> unless you have a kernel-mode driver or inject a DLL into the process which is a topic for another day

https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#raise-the-clock-interrupt-frequency-timer-resolution
