### ISSUE TITLE
Disable Nvidia Telemetry Typo

### ISSUE THREAD

**Issue by Jiembow** [amitxv/PC-Tuning#158]
I believe the following command 
`reg add "HKLM\SYSTEM\CurrentControlSet\Services\nvlddmkm\Global\Startup" /v "SendTelemetryData" /t REG_DWORD /d "0" /f`

 should be 
`reg add "HKLM\SYSTEM\CurrentControlSet\Services\nvlddmkm\Global\Startup\SendTelemetryData" /t REG_DWORD /d "0" /f`

 considering **_SendTelemetryData_** is already present as a key under **_Startup_** and the first command adds it as a DWORD under **_Startup_**

**Comment by amitxv** [comment]
You seem to be correct, WPA doesn't specify the key when tracing registry queries so it wasn't easy to tell. I ran another boot trace and neither ``SendTelemetryData`` or ``OptInOrOutPreference`` are being queried on the latest driver. I'm contemplating whether they should be in the guide at all now.
