### ISSUE TITLE
Autoruns Yellow Entries

### ISSUE THREAD

**Issue by SVSQUVSH** [amitxv/PC-Tuning#159]
This step described in the cleanup section of the guide is problematic: "Remove all obsolete entries with a yellow label and run with C:\bin\NSudo.exe if you encounter any permission errors". 

Some entries with a yellow color are important system files and should not be removed or disabled. This can cause system instability. 

Example: wow64cpu.dll

It will show as a yellow entrie in autoruns with the message " file not found ", even tho this is a important .dll and it's critical to make 32bit processes run on a 64bit processor.

**Comment by amitxv** [comment]
Autoruns is correct in labelling these as non existent files. How can these be important system files if they do not exist out of the box?

![image](https://github.com/amitxv/PC-Tuning/assets/86924251/9652e58b-97af-41ec-9938-c090c98c4704)

**Comment by amitxv** [comment]
Addressed in https://github.com/amitxv/PC-Tuning/commit/ebad3f9cbae7aa5b16a0f9b2d9567acf820315d2.
