### ISSUE TITLE
Add Security Warnings

### ISSUE THREAD

**Issue by amitxv** [amitxv/PC-Tuning#162]
Warnings have already been added throughout post-install.md, but not for the changes in the registry files as a more user-friendly method is being worked on to make these optional and to add warnings for each change: 

- Prevent Windows Marking File Attachments With Information About Their Zone of Origin
- Disable Windows Defender
- Disable Windows Update
- smartscreen.exe - this gets *disabled* by renaming the binary so that it can't run. It can be grouped with the registry files as that is where the rest of the defender related components get disabled by using an invalid IEFO Debugger entry
- Disable UAC - Technically, this isn't optional since I'm not aware of a method to run PowerShell scripts at startup with admin privileges without Task Scheduler (search for ``shell:startup`` in this repo)

**Comment by SnowzNZ** [comment]
> Disable UAC - Technically, this isn't optional since I'm not aware of a method to run PowerShell scripts at startup with admin privileges without Task Scheduler (search for shell:startup in this repo)

Create a shortcut with this as the target:
`PowerShell Start-Process PowerShell -Verb runAs <script path>`

**Comment by amitxv** [comment]
Security warnings added in https://github.com/amitxv/PC-Tuning/commit/22cc344a3440a7073499ebbe056aeb35fb75bf13.

**Comment by amitxv** [comment]
> > Disable UAC - Technically, this isn't optional since I'm not aware of a method to run PowerShell scripts at startup with admin privileges without Task Scheduler (search for shell:startup in this repo)
> 
> By disable UAC do you mean using the control panel slider or the `EnableLUA` registry key?
> 
> If you're using the control panel slider you can just create a shortcut with the following as the target: `PowerShell Start-Process PowerShell -Verb runAs <script path>`

https://github.com/amitxv/PC-Tuning/blob/22cc344a3440a7073499ebbe056aeb35fb75bf13/bin/apply-registry.ps1#L169-L174

I will try the method you mentioned with PowerShell to run scripts with admin privileges later.

**Comment by amitxv** [comment]
@SnowzNZ This seems to work well. Only tradeoff is the UAC prompt at boot which is acceptable. I will look into refactoring the documentation to use this method instead. Thanks.
