### ISSUE TITLE
win11 taskbar break

### ISSUE THREAD

**Issue by pidjan** [amitxv/PC-Tuning#172]
by disabling `camsvc (Capability Access Manager Service)` - windows 11 taskbar breaks like showed on image
![image](https://github.com/amitxv/PC-Tuning/assets/127833246/1f4dbc0c-b46d-46b1-afd8-f090ae6cf01b)
to fix win11 taskbar, just set camsvc startup type to Manual.

**Comment by amitxv** [comment]
I was able to reproduce and has been addressed in https://github.com/amitxv/PC-Tuning/commit/e5be7689a798ea3667f39f56fb835096551d7f5d, thanks.
