### ISSUE TITLE
Make DWM script more robust

### ISSUE THREAD

**Issue by amitxv** [amitxv/PC-Tuning#174]
Currently, the DWM script depends on the user running ``Services-Disable.bat`` to prevent problematic binaries from running such as ``TextInputHost.exe``. It would be better if those problematic binaries are handled directly in the DWM script.

**Comment by UseUrSk1lz** [comment]
Before begining the main functions, explorer could be killed, then kill the respective problematic binaries.
Or if they cannot be killed easily a third party tool such as PsSuspend could suspend them before begining the main execution of the script.


_Though this is a shot in the dark, I am not familiar with powershell scripting_

**Comment by Aetopia** [comment]
> Before begining the main functions, explorer could be killed, then kill the respective problematic binaries. Or if they cannot be killed easily a third party tool such as PsSuspend could suspend them before begining the main execution of the script.
> 
> _Though this is a shot in the dark, I am not familiar with powershell scripting_

PowerShell can leverage .NET itself so suspending them is entirely possible via P/Invoke to use the Windows API.

https://devblogs.microsoft.com/scripting/use-powershell-to-interact-with-the-windows-api-part-1/
