### ISSUE TITLE
Legacy Context Reg Keys didn't Apply

### ISSUE THREAD

**Issue by SVSQUVSH** [amitxv/PC-Tuning#176]
I noticed that the two legacy context menu reg keys didn't apply. Looks like it couldn't create the new class id. 

The reg keys are located in the Windows 11+ Registry file, under "restore old context menu".

Using Windows 11 Pro, 

thanks

**Comment by amitxv** [comment]
There are a few problems with the description of your issue.

1. The structure of how registry files are maintained in this project has changed significantly. There are no longer any individual registry files such as ``Windows11+.reg`` hence you have an outdated clone of the repository
2. Even when individual ``.reg`` files were being stored in the repository, the user is not meant to interact with them directly. The ``apply-registry.ps1`` does everything for you. This was the primary motivation of not storing ``.reg`` files in the repo as it causes confusion for uninformed users
3. Regarding uninformed users, the ``apply-registry.ps1`` script applies each key once as the current user and trusted installer. I assume you did not use NSudo, Minsudo or similar to merge the registry file as trusted installer hence the permission errors
4. Upon refactoring how the registry keys are managed in this project, I have moved subjective changes such as this to gist containing my personal collection of registry keys which can be found [here](https://gist.github.com/amitxv/4ab50141be2b124dc4c7d326a7ce45ea)

**Comment by SVSQUVSH** [comment]
I did download your repository 2 days ago and followed your guide step by step. Im not referring to the online repository.

It doesn't show each individual registry file on github, but I can review it on desktop. It shows me all the registry registry files beginning from windows 7 to windows 11, some with the +. 

As of my knowledge, and as you wrote in the guide, the registry files get merged. Don't they get merged from the "registry" inside the PC-Tuning folder, where the files are stored? Please correct me if i'm wrong.

In your guide, it doesn't tell the user to use Nsudo, or Minsudo to use apply-registry.ps1. Quote: 

" - Open PowerShell as administrator and enter the command below

    ```powershell
    C:\bin\apply-registry.ps1
    ``` "
Thank you

**Comment by SVSQUVSH** [comment]
Nvm, I misunderstood. I always thaught apply-registry.ps1 works together with the reg files in the registry folder. I see now in the apply registry, there isn't such tweak to disable the legacy context menu and it was my mistake to look into the reg files for analyzing this. 
Thanks

**Comment by SVSQUVSH** [comment]
Nvm, I misunderstood. I always thaught apply-registry.ps1 works together with the reg files in the registry folder. I see now in the apply registry, there isn't such tweak to disable the legacy context menu and it was my mistake to look into the reg files for analyzing this.
Thanks
